### ISSUE TITLE
handle InvalidSignatureError

### ISSUE THREAD

**Issue by spaceone** [datalayer-experiments/tornado-keycloak#3]
When I access /jwk I get:

```
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/usr/lib/python3/dist-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/fbest/git/tornado-keycloak/tornado_oidc/handlers.py", line 154, in get
        await self.get_current_user()
      File "/home/fbest/git/tornado-keycloak/tornado_oidc/handlers.py", line 140, in get_current_user
        payload = jwt.decode(bearer, public_key, algorithms='RS256', options={'verify_aud': False})
      File "/usr/lib/python3/dist-packages/jwt/api_jwt.py", line 92, in decode
        jwt, key=key, algorithms=algorithms, options=options, **kwargs
      File "/usr/lib/python3/dist-packages/jwt/api_jws.py", line 156, in decode
        key, algorithms)
      File "/usr/lib/python3/dist-packages/jwt/api_jws.py", line 223, in _verify_signature
        raise InvalidSignatureError('Signature verification failed')
    jwt.exceptions.InvalidSignatureError: Signature verification failed
```

Hm, what could be the cause? A programatic error or a configuration error?
I see hardcoded algorhithms in the code. (RSA / RS256)

**Comment by echarles** [comment]
> Hm, what could be the cause? A programatic error or a configuration error?

Maybe both? I remember having hard time with that and not sure if I made it work.

`algorithms='RS256', options={'verify_aud': False}` is worth to be tuned.
